[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  publish = "."
  functions = "netlify/functions"

# URL Kısaltmaları
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/admin-login.html"
  status = 200

